#!/bin/bash
#NAME="batt_stat"
#BLURB="Display battery state, time|percentage remaining until empty|full"
#SOURCE="https://github.com/vonbrownie/homebin/blob/master/batt_stat"

upower -i $(upower -e | grep BAT) | \
    grep --color=never -E 'state|to\ full|to\ empty|percentage'
