#!/bin/bash
#NAME="bye"
#BLURB="tasks performed on shutdown"
#SOURCE="https://github.com/vonbrownie/homebin/blob/master/bye"
set -eu

Task_backup() {
/home/dwa/bin/teleportHome.sh 192.168.1.2:/home/dwa/backup/dwa.bak/home/
}

# (O< .: Start
# (/)_
Task_backup
sleep 2; sudo /sbin/poweroff
