#!/bin/bash

NAME="dldsply"
BLURB="enable|disable extended desktop using XRandR"
GIT_SRC="https://github.com/vonbrownie/homebin/blob/master/dldsply"

dsply1=$(xrandr | grep " connected" | awk 'FNR == 1 {print $1}')
dsply2=$(xrandr | grep " connected" | awk 'FNR == 2 {print $1}')
confDsply="xrandr --output $dsply1 --auto --output $dsply2 --primary"

testLib() {
# A library of functions for shell scripts
local libName="Library.sh"
local libSrc="https://github.com/vonbrownie/homebin/blob/master/${libName}"
local lib="$HOME/bin/${libName}"
if [[ -e $lib ]]
then
    . $lib
else
    echo -e "\nI require '$lib' to do my magic."
    echo "SOURCE"
    echo -e "\t$libSrc"
    echo -e "Download script from above link and place in $HOME/bin.\n"
    exit 1
fi
}

shDetails() {
echo "$( penguinista ) .: $NAME -- $BLURB :."
echo "USAGE"
echo -e "\t$NAME [OPTION]"
echo "OPTIONS"
echo -e "\t-h\tdescription and options"
echo -e "\t-q\tdisable extended desktop"
echo "SOURCE"
echo -e "\t<${GIT_SRC}>\n"
}

runOpt() {
while getopts ":hq" OPT
do
    case $OPT in
        h)
            shDetails
            exit
            ;;
        q)
            $confDsply --off
            exit
            ;;
        *)
            echoRed "$( penguinista ) .: Invalid option '-$OPTARG'."
            exit 1
            ;;
    esac
done
}

confDesk() {
if [[ -n $dsply2 ]]; then $confDsply --auto --right-of $dsply1; fi
}

#: START
testLib
runOpt "$@"
confDesk
