#!/bin/bash
#
#> Daniel Wayne Armstrong
#> https://github.com/dwarmstrong/homebin
#> https://www.dwarmstrong.org
#
# Personal wiki with auto-backup.

set -eu

WIKI="$HOME/doc/wiki"

if [[ -n $(git -C "$WIKI" status --porcelain) ]]; then
    git -C "$WIKI" add --all && git -C "$WIKI" commit -m 'save'
fi
nvim -c VimwikiIndex
