#!/bin/bash
# ~/bin/dlg
#
# Source: https://github.com/vonbrownie/homebin/blob/master/dlg
set -eu

# Personal wiki with auto-backup. Requires: neovim, vimwiki, git
WIKI="$HOME/doc/wiki"

if [[ -n $(git -C "$WIKI" status --porcelain) ]]; then
    git -C "$WIKI" add --all && git -C "$WIKI" commit -m 'save'
fi
nvim -c VimwikiIndex
