#!/bin/bash

# Name: dlg - personal wiki with auto-backup
# Requires: neovim, vimwiki, git
# Link: https://github.com/vonbrownie/homebin/

set -eu

WIKI="$HOME/doc/wiki"

if [[ -n $(git -C $WIKI status --porcelain) ]]; then
    git -C $WIKI add --all && git -C $WIKI commit -m 'save'
fi
nvim -c VimwikiIndex
