#!/bin/bash
# Written by: Daniel Wayne Armstrong - https://www.circuidipity.com

set -eu

PROG="genpkglst"
DESC="generate a list of installed Debian packages on $HOSTNAME"
DESTINATION="."

Run_options() {
while getopts ":hd:" OPT
do
    case $OPT in
        h)
            printf 'DESCRIPTION\n'
            printf '\t%s\n' "$PROG - ${DESC}"
            printf 'USAGE\n'
            printf '\t%s\n' "$PROG [OPTION] [DESTINATION]"
            printf 'OPTIONS\n'
            printf '\t-d\n'
            printf '\t\tsave to DESTINATION\n'
            printf '\t-h\n'
            printf '\t\tthis help message\n'
            printf 'EXAMPLE\n'
            printf '\t%s\n' "Create a package list and save to $HOME ..."
            printf '\t\t%s\n' "$ $PROG -d $HOME"
            exit 0
            ;;
        d)
            DESTINATION=$2
            ;;
        *)
            printf '%s\n' "'-${OPTARG}' is an invalid option."
            exit 1
            ;;
    esac
done
}

Debian_codename() {
lsb_release -c | awk -F: '{print $NF}' | sed 's/[[:blank:]]//g'
}

Generate_list() {
local CODENAME
    CODENAME=$( Debian_codename )
local PKG_LIST
    PKG_LIST="${DESTINATION}/${HOSTNAME}_pkg_list.${CODENAME}.$(date +%F)"
touch "$PKG_LIST"
# Generate list of installed packages
dpkg --get-selections > "$PKG_LIST"
sed -i '/deinstall/d' "$PKG_LIST"
# Remove packages not found in the Debian archives
#if [[ -x $APT_SHOW ]]; then
#    local ARRAY_PNF
#        ARRAY_PNF=( $($APT_SHOW | grep -v "$CODENAME" | awk -F: '{print $1}') )
#    for package in "${ARRAY_PNF[@]}"
#    do
#        sed -i "/$package/d" "$PKG_LIST"
#    done
#else
#    L_echo_red "\n$( L_penguin ) .: ERROR: Command '$APT_SHOW' not found."
#fi
}

Run_options "$@"
Generate_list
