#!/bin/bash
# ~/bin/keyboardconf
#
# Source: https://github.com/vonbrownie/homebin/blob/master/keyboardconf
set -eu

XBIND="${HOME}/.xbindkeysrc"
XINPUT="${HOME}/.xinput.conf"
XMOD="${HOME}/.xmodmap"

# Bind commands to certain keys or key combos
if [[ -f $XBIND ]]; then
    xbindkeys --file "$XBIND"
fi

# Xorg uses libinput library and driver to handle input devices
if [[ -f $XINPUT ]]; then
    $XINPUT
fi

# Modify key mappings
if [[ -f $XMOD ]]; then
    xmodmap "$XMOD"
fi
