#!/bin/bash
set -eu

scriptName="myRsync"
scriptBlurb="sync SOURCE to DESTINATION"
scriptProject="https://github.com/vonbrownie/homebin"
scriptSrc="${scriptProject}/blob/master/${scriptName}"

syncOpt="--verbose"
syncExc=""
syncSrc="${@: -2:1}"
syncDes="${@: -1}"

testLibrary() {
# A library of functions for shell scripts
local libName="Library.sh"
local libSrc="${scriptProject}/blob/master/${libName}"
local lib="$HOME/bin/${libName}"
if [[ -e $lib ]]
then
    . $lib
else
    echo -e "\nI require '$lib' to do my magic."
    echo "SOURCE"
    echo -e "\t$libSrc"
    echo -e "Download script from above link and place in $HOME/bin.\n"
    exit 1
fi
}

scriptDetails() {
echo "$( penguinista ) .: $scriptName -- $scriptBlurb :."
echo "USAGE"
echo -e "\t$scriptName [OPTION] [SOURCE] [DESTINATION]"
echo "OPTIONS"
echo -e "\t-h\tdescription and options"
echo -e "\t-d\tdelete extraneous files from destination"
echo -e "\t-e\texclude PATTERN"
echo -e "\t-n\tperform a trial run with no changes made"
echo -e "\t-p\tshow progress during transfer"
echo -e "\t-S\t'Snapshot mode' (implies '--hard-links --numeric-ids --delete')"
echo -e "\t-W\tcompare mod-times with reduced accuracy (useful for transfers "`
    `"to FAT16|32 filesystems)"
echo "EXAMPLE"
echo -e "\tPerform a sample run and view the changes that would be made:"
echo -e "\t\t$scriptName -nd ${HOME}/ remote:~/backup/"
echo -e "\tExclude 'old_photo' directories:"
echo -e "\t\t$scriptName -e old_photo ${HOME}/ /media/sdb1/"
echo "SOURCE"
echo -e "\t<${scriptSrc}>\n"
}

runOptions() {
while getopts ":hde:npSW:" OPT
do
    case $OPT in
        h)
            scriptDetails
            exit 0
            ;;
        d)
            syncOpt="$syncOpt --delete"
            ;;
        e)
            syncExc="$syncExc --exclude=${OPTARG}"
            ;;
        n)
            syncOpt="$syncOpt --dry-run"
            ;;
        p)
            syncOpt="$syncOpt --human-readable --progress"
            ;;
        S)
            syncOpt="$syncOpt --hard-links --numeric-ids --delete"
            ;;
        W)
            # See http://rsync.samba.org/FAQ.html#2 about using the
            # "--modify-window=1" script_opts to better manage
            # modification times when using rsync between Linux
            # and FAT32 filesystems
            syncOpt="${syncOpt} --modify-window=1"
            ;;
        :)
            echoRed "$( penguinista ) .: Option '-$OPTARG' missing argument."
            exit 1
            ;;
        *)
            echoRed "$( penguinista ) .: Invalid option '-$OPTARG'"
            exit 1
            ;;
    esac
done
}

addKey() {
local key="${HOME}/.keychain/${HOSTNAME}-sh"
if [ -e $key ]; then . $key; fi
}

excludeFrom() {
local exclude="$HOME/.rsyncExclude"
if [ -e $exclude ]; then syncExc="--exclude-from=$exclude $syncExc"; fi
}

sync() {
if [[ $syncOpt == *modify-window* ]]
then
    syncOpt="${syncOpt} --recursive --links --times"
else
    syncOpt="${syncOpt} --archive"
fi
addKey
excludeFrom
rsync $syncOpt $syncExc $syncSrc $syncDes
auRevoir
}

#: START
testLibrary
runOptions "$@"
sync
