#!/bin/bash
#
#> Daniel Wayne Armstrong
#> https://github.com/dwarmstrong/homebin
#> https://www.dwarmstrong.org
#

set -euo pipefail

savedir="${HOME}/code/arch"
savefile="${savedir}/arch-pkglist-$(hostname)-$(date +%FT%H%M)"
savefileaur="${savedir}/arch-pkglist.aur-$(hostname)-$(date +%FT%H%M)"

# remove old lists
rm ${savedir}/arch-pkglist*

# generate a list of all explicitly installed pkgs;
# excluding foreign packages (e.g. from AUR)
pacman -Qqen > $savefile

# generate a list of AUR and other foreign pkgs explicitly installed
pacman -Qqem > $savefileaur

# see: https://wiki.archlinux.org/index.php/Pacman/Tips_and_tricks#List_of_installed_packages
