#!/bin/bash
#
#> Daniel Wayne Armstrong
#> https://github.com/dwarmstrong/homebin
#> https://www.dwarmstrong.org
#

set -euo pipefail

savefile="$HOME/code/arch/pkglist/arch-pkglist-$(hostname)-$(date +%FT%H%M)"
saveffile="$HOME/code/arch/pkglist/arch-fpkglist-$(hostname)-$(date +%FT%H%M)"

# generate a list of all explicitly installed pkgs;
# excluding foreign packages (e.g. from AUR)
pacman -Qqen > $savefile

# generate a list of AUR and other foreign pkgs explicitly installed
pacman -Qqem > $saveffile

# see: https://wiki.archlinux.org/index.php/Pacman/Tips_and_tricks#List_of_installed_packages
