#!/bin/bash
scriptName="paVolume"
scriptBlurb="pulseaudio volume control"
scriptProject="https://github.com/vonbrownie/homebin"
scriptSrc="${scriptProject}/blob/master/${scriptName}"

# REQUIRES: pulseaudio, pulseaudio-utils, pamixer, volnoti
# pactl - control a running pulseaudio server                                      
# 'pactl list sinks' - retrieve info                                                 
# pamixer - pulseaudio command line mixer
sinkMute="pactl set-sink-mute @DEFAULT_SINK@"
sinkVol="pactl set-sink-volume @DEFAULT_SINK@"
getVol="volnoti-show $(pamixer --get-volume)"

scriptDetails() {
echo "NAME"
echo -e "\t$scriptName - $scriptBlurb :."
echo "USAGE"
echo -e "\t$scriptName [OPTION]"
echo "OPTIONS"
echo -e "\t-h\tscript details"
echo -e "\t-m\ttoggle volume mute"
echo -e "\t-u\tincrease volume +10%"
echo -e "\t-d\tdecrease volume -10%"
echo "SOURCE"
echo -e "\t<${scriptSrc}>"
}

volMute() {
$sinkMute toggle; [[ $(pamixer --get-mute) = true ]] \
    && volnoti-show -m || $getVol
}

volUp() {
$sinkVol -- +10%; $getVol
}

volDown() {
$sinkVol -- -10%; $getVol
}

runOptions() {
while getopts ":hmud" OPT
do
    case $OPT in
        h)
            scriptDetails
            exit 0
            ;;
        m)
            volMute
            exit 0
            ;;
        u)
            volUp
            exit 0
            ;;
        d)
            volDown
            exit 0
            ;;
        *)
            echo "Invalid option '-$OPTARG'"
            exit 1
            ;;
    esac
done
}

#: START
runOptions "$@"
