#!/bin/bash
set -eu

NAME="sh2"
BLURB="sync $HOME to DESTINATION"
GIT_SRC="https://github.com/vonbrownie/homebin/blob/master/sh2"

R_EXCLUDE="--exclude=*[Cc]ache* --exclude=*[Tt]humbnail* --exclude=*[Tt]rash*"
R_OPT="--delete --archive"
R_DEST=""

testLib() {                                                                    
# A library of functions for shell scripts
local libName="Library.sh"
local libSrc="https://github.com/vonbrownie/homebin/blob/master/${libName}"
local lib="$HOME/bin/${libName}"
if [[ -e $lib ]]; then
    . $lib
else
    echo -e "\nI require '$libName' to do my magic."
    echo "SOURCE"
    echo -e "\t$libSrc"
    echo -e "Download script from above link and place in $HOME/bin.\n"
    exit 1
fi
}

runOpt() {
while getopts ":npve:d:" OPT
do
    case $OPT in
        n)
            R_OPT="$R_OPT --dry-run"
            ;;
        p)
            R_OPT="$R_OPT --human-readable --progress"
            ;;
        v)
            R_OPT="$R_OPT --verbose"
            ;;
        e)
            R_EXCLUDE="$R_EXCLUDE --exclude=${OPTARG}"
            ;;
        d)
            R_DEST="$OPTARG"
            ;;
        :)
            echoRed "$( penguinista ) .: Option '-$OPTARG' missing argument."
            exit 1
            ;;
        *)
            echoRed "$( penguinista ) .: Invalid option '-$OPTARG'."
            exit 1
            ;;
    esac
done
}

h2default() {
rsync $R_EXCLUDE $R_OPT $HOME/ $R_DEST
}

h2partial() {
rsyncDir=( Downloads code doc image jukebox share video )
for i in "${rsyncDir[@]}"
do
    rsync $R_EXCLUDE $R_OPT $HOME/$i/ ${R_DEST}${i}/
done
}

h2d() {
if [[ $R_DEST == "cruithne.lan:~/" ]] || [[ $R_DEST == "summanus.lan:~/" ]]; then
    h2partial
else
    h2default
fi
}


#: START
testLib
runOpt "$@"
h2d
