#!/bin/bash
# Written by: Daniel Wayne Armstrong - https://www.circuidipity.com

set -eu

PROG="synchome"
DESC="sync $HOME to DESTINATION"
ARGS="$#"
DESTINATION="${*: -1}"
RSYNC_OPTS="--archive --verbose --delete --exclude=*[Cc]ache*/ \
--exclude=*[Tt]rash*/"

Run_options() {
while getopts ":hn" OPT
do
    case $OPT in
        h)
            printf 'DESCRIPTION\n'
            printf '\t%s\n' "$PROG - ${DESC}"
            printf 'USAGE\n'
            printf '\t%s\n' "$PROG [OPTION] DESTINATION"
            printf 'OPTIONS\n'
            printf '\t-h\n'
            printf '\t\tthis help message\n'
            printf '\t-n\n'
            printf '\t\tperform a trial run with no changes made\n'
            printf 'EXAMPLE\n'
            printf '\t%s\n' "Sync $HOME to a mounted external USB drive ..."
            printf '\t\t%s\n' "$ ${PROG} /media/sdb1/backup/"
            exit 0
            ;;
        n)
            RSYNC_OPTS="$RSYNC_OPTS --dry-run"
            ;;
        *)
            printf '%s\n' "'-${OPTARG}' is an invalid option."
            exit 1
            ;;
    esac
done
}

Sync_home() {
    # Test that DESTINATION has been specified
    if [[ "$ARGS" -eq 0 ]]; then
        printf 'ERROR: No DESTINATION specified.\n'
        exit 1
    fi
    # Test that DESTINATION is a valid directory
    if [[ -d "$DESTINATION" ]]; then
        #printf '%s\n' "rsync $RSYNC_OPTS ${HOME}/ ${DESTINATION}/" #TEST
        rsync $RSYNC_OPTS ${HOME}/ ${DESTINATION}/
    else
        printf '%s\n' "ERROR: '$DESTINATION' not found."
        exit 1
    fi
}

Run_options "$@"
Sync_home
