#!/bin/bash
set -eu

NAME="teleportHomeTo"
BLURB="sync $HOME to DESTINATION:$HOME"
GIT_SRC="https://github.com/vonbrownie/homebin/blob/master/teleportHomeTo"
SYNC_OPT="--archive --verbose --delete"
INCLUDE_ALL="0"
LIST="$HOME/.teleportHomeTo" # list of items to include (and exclude) from sync
DESTINATION="${!#}"

testLib() {                                                                    
# A library of functions for shell scripts
local libName="Library.sh"
local libSrc="https://github.com/vonbrownie/homebin/blob/master/${libName}"
local lib="$HOME/bin/${libName}"
if [[ -e $lib ]]; then
    . $lib
else
    echo -e "\nI require '$libName' to do my magic."
    echo "SOURCE"
    echo -e "\t$libSrc"
    echo -e "Download script from above link and place in $HOME/bin.\n"
    exit 1
fi
}

runOpt() {
while getopts ":ane:" OPT
do
    case $OPT in
        a)
            INCLUDE_ALL="1"
            ;;
        n)
            SYNC_OPT="$SYNC_OPT --dry-run"
            ;;
        *)
            echoRed "$( penguinista ) .: Invalid option '-$OPTARG'."
            exit 1
            ;;
    esac
done
}

teleport() {
local EXCLUDE="--exclude=*[Cc]ache/ --exclude=*[Tt]rash"
if [[ $INCLUDE_ALL == "1" ]]; then
    rsync $SYNC_OPT $EXCLUDE $HOME/ $DESTINATION
else
    rsync $SYNC_OPT --include-from=$LIST $HOME/ $DESTINATION
fi
}

#: START
testLib
testConnect
runOpt "$@"
teleport
penguinista
