#!/bin/bash
#
# DESCRIPTION="capture screenshot of a virtualbox session"

vboxBin="/usr/bin/VBoxManage"
vboxSave="$HOME/tmp"
vboxDate="vbox.$(date +%FT%H:%M:%S.png)"

# Find out the unique identifier (UUID) of the running VM; this assumes that
# only a single VM is running
vboxName="$($vboxBin \
    list runningvms --long | grep -m 1 "UUID:" | awk '{print $2}')"

$vboxBin controlvm $vboxName screenshotpng ${vboxSave}/${vboxDate}
