#!/bin/bash
# NAME="xtra"
# BLURB="xinit extra config"
# SOURCE="https://github.com/vonbrownie/homebin"

Conf_dp() {
    # Standby/Suspend/Off
    #xset dpms 1800 1800 1800
    xset -dpms
    xset s noblank
    xset s off
}

Conf_kb() {
    #
    # TP keyboard + TrackPoint: "Device Accel Constant Deceleration" configures
    # the sensitivity of the trackpoint. Find <id> with ...
    #   xinput list | grep pointer
    # ... and <id> properties with ...
    #   xinput list-props <id>
    #
    local tpPointer=$(xinput list | grep "TrackPoint.*pointer")
    local tpID=$(echo $tpPointer | awk '{print $11}' | cut -d'=' -f2)
    if [[ $tpPointer ]]; then
        { xinput set-prop $tpID "Device Accel Constant Deceleration" 0.30; }
    fi
    # Caps_Lock modified to Backspace... make it a repeating key
    #xset r 66
}

Conf_host() {
    if [[ $HOSTNAME = ull* ]]; then
        nm-applet
    fi
}

# START
Conf_dp
Conf_kb
Conf_host
