#!/bin/bash
# NAME="yt-audio"
# BLURB="Download and convert online audio"
# SOURCE="https://github.com/vonbrownie/homebin"
set -eu

ytOpt="-x --audio-format mp3 --audio-quality 0 --restrict-filenames"
ytTitle="%(title)s-%(upload_date)s.%(ext)s"

testLibrary() {
# A library of functions for shell scripts
local libName="Library.sh"
local libSrc="https://github.com/vonbrownie/homebin/blob/master/Library.sh"
local lib="$HOME/bin/${libName}"
if [[ -e $lib ]]
then
    . $lib
else
    echo -e "\nI require '$lib' to do my magic."
    echo "SOURCE"
    echo -e "\t$libSrc"
    echo -e "Download script from above link and place in $HOME/bin.\n"
    exit 1
fi
}

# START
testLibrary
for url in "$@"
do
    youtube-dl $ytOpt --output $ytTitle $url
done
penguinista
