#!/bin/bash
# NAME="yt-audio"
# BLURB="Download and convert online audio"
# SOURCE="https://github.com/vonbrownie/homebin/blob/master/yt-audio"
set -eu

ytOpt="-x --audio-format mp3 --audio-quality 0 --restrict-filenames"
ytTitle="%(title)s-%(upload_date)s.%(ext)s"


Conf_homebin_lib() {
local LIB="https://github.com/vonbrownie/homebin/blob/master/Library.sh"
local HOMEBIN="$HOME/bin"
# A library of functions for shell scripts
local HOMEBIN_LIB="$HOMEBIN/Library.sh"
if [[ -x "$HOMEBIN_LIB" ]]; then
    # shellcheck source=/dev/null
    . $HOMEBIN_LIB
else
    echo -e "\n(O<"
    echo "(/)_ .: ERROR: I require '$HOMEBIN_LIB' to do my magic."
    echo "Download script from $LIB and place in $HOMEBIN."
    exit 1
fi
}


# START
Conf_homebin_lib
for url in "$@"
do
    youtube-dl $ytOpt --output $ytTitle $url
done
L_all_done
